apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rps
type: Opaque
stringData:
  POSTGRES_DB: players
  POSTGRES_USER: players_user
  POSTGRES_PASSWORD: change-me-too
  DATABASE_URL: postgres://players_user:change-me-too@postgres:5432/players?sslmode=disable
