apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-s3-backup
  namespace: rps
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgres-s3-backup
              image: keseljoa/rps-cloud-native-postgres-backup:latest
              imagePullPolicy: Always
              env:
                - name: PGHOST
                  value: postgres
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: AWS_DEFAULT_REGION
                - name: S3_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: S3_BUCKET
                - name: S3_PREFIX
                  valueFrom:
                    secretKeyRef:
                      name: s3-backup-secret
                      key: S3_PREFIX
