apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-secret
  namespace: rps
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_DEFAULT_REGION: eu-north-1
  S3_BUCKET: replace-me
  S3_PREFIX: rps-cloud-native/postgres
